# Generated by Django 2.2.5 on 2019-09-18 19:59

import django.core.validators
from django.db import migrations, models
import ipset.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.GenericIPAddressField()),
                ('entry_id', models.CharField(max_length=100, unique=True)),
                ('expires', models.DateTimeField(default=ipset.models._new_expires)),
                ('sets', models.ManyToManyField(to='ipset.Set')),
            ],
        ),
    ]
